#!/usr/bin/env python
"""
A program to generate a simulated pulsar profile as a .ast file to use an an input for the inject_pulsar program.
"""


from math import pi,radians,degrees
import numpy as np
from numpy import random
#This code allows the catching of integer under/overflows generated by numpy as though they were exceptions
import warnings
warnings.filterwarnings('error')
np.seterr(all = 'warn')

def make_prof():
    class Success(Exception):
        pass
    while True:
        try:
            out=np.zeros(1024)
            phase=np.linspace(0,2*pi,1024,endpoint=False)
            ncomponents=random.randint(2,8)
            nmp=0
            nip=0
            for icomp in range(ncomponents):
                A = random.lognormal()
                width = random.chisquare(2)*pi/64.0 # put a floor?

                po = random.normal(0,pi/4)
                ip = (random.uniform() < 0.08)
                if ip:
                    po+=pi
                    nip+=1
                    width *= nip
                    if nip==1:
                        A*=2
                else:
                    nmp+=1
                    width *= nmp

                    if nmp==1:
                        A*=2

                comp = np.exp(np.cos(phase-po)/width)
                comp /= comp.sum()
                out += A*comp
            out /= out.sum()
            raise Success
        except Warning:
            continue
        except Success:
            return out

if __name__=="__main__":
    out = make_prof()
    for o in out:
       print o
